#ifndef INCLUDED_CALLBACK_H
#define INCLUDED_CALLBACK_H

#include "d2gelib/d2server.h"

typedef enum {
	D2GS_CALLBACK_ABI_109D,
	D2GS_CALLBACK_ABI_109B,
	D2GS_CALLBACK_ABI_100,
	D2GS_CALLBACK_ABI_101
} D2GSCALLBACKABI;

extern LPEVENTCALLBACKTABLE EventCallbackTableInit(D2GSCALLBACKABI callbackAbi);

#endif
